# Generated by Django 3.1.12 on 2022-11-20 14:21

import SmartDjango.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', SmartDjango.models.fields.CharField(max_length=10, unique=True)),
                ('nick', SmartDjango.models.fields.CharField(max_length=10)),
                ('token', SmartDjango.models.fields.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
    ]
