# Generated by Django 5.2.12 on 2026-03-07 11:06

import Account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=10, unique=True, validators=[Account.validators.AccountValidator.name]),
        ),
    ]
