# Generated by Django 5.2.12 on 2026-03-07 11:06

import Config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={},
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(max_length=255, unique=True, validators=[Config.validators.ConfigValidator.key]),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(max_length=255, validators=[Config.validators.ConfigValidator.value]),
        ),
    ]
